import { jsPDF } from 'jspdf';
import { ExamResult, CertificateRequest, TimetableEntry } from '../types.ts';

/**
 * Generates a beautiful official marksheet PDF using jsPDF
 */
export function exportResultPDF(studentName: string, rollNo: string, results: ExamResult) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  // Border decoration
  doc.setDrawColor(26, 58, 92);
  doc.setLineWidth(1);
  doc.rect(5, 5, 200, 287);
  doc.rect(6, 6, 198, 285);

  // Logo placeholder & Header
  doc.setFillColor(26, 58, 92);
  doc.rect(15, 12, 180, 26, "F");

  // School branding
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(255, 255, 255);
  doc.text("RAJYAKRIT OMAR GIRL'S +2 SCHOOL", 105, 20, { align: "center" });

  doc.setFontSize(10);
  doc.setTextColor(245, 158, 11); // Amber accent
  doc.text("Bishnupur, Begusarai, Bihar - UDISE ID: 10201001210", 105, 26, { align: "center" });
  doc.text("Department of Education, Government of Bihar", 105, 32, { align: "center" });

  // Certificate Title
  doc.setFontSize(14);
  doc.setTextColor(26, 58, 92);
  doc.text("MATRICULATION ASSESSMENTS REPORT CARD", 105, 48, { align: "center" });

  doc.setLineWidth(0.5);
  doc.setDrawColor(212, 82, 42); // #D4522A
  doc.line(40, 52, 170, 52);

  // Student Details Panel
  doc.setFillColor(247, 243, 238);
  doc.rect(15, 58, 180, 24, "F");
  doc.setDrawColor(220, 220, 220);
  doc.rect(15, 58, 180, 24, "S");

  doc.setFont("Helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(30, 30, 30);
  doc.text(`Student Name: ${studentName}`, 20, 64);
  doc.text(`Class Roll No: ${rollNo}`, 130, 64);
  doc.text(`Exam Scale: ${results.examNameEn}`, 20, 71);
  doc.text(`Session: ${results.academicYear}`, 130, 71);
  doc.text(`School Code: 26011 (BSEB)`, 20, 77);
  doc.text(`Result Status: ${results.resultStatus}`, 130, 77);

  // Marks Table Header
  let y = 92;
  doc.setFillColor(26, 58, 92);
  doc.rect(15, y, 180, 8, "F");

  doc.setFont("Helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.text("Academic Subject", 20, y + 5.5);
  doc.text("Full Marks", 85, y + 5.5);
  doc.text("Pass Marks", 125, y + 5.5);
  doc.text("Obtained", 165, y + 5.5);

  // Subject rows
  const subjects = results.subBlockMarks || [
    { subjectEn: 'Hindi', fullMarks: 100, passMarks: 30, marksObtained: 84 },
    { subjectEn: 'Sanskrit', fullMarks: 100, passMarks: 30, marksObtained: 78 },
    { subjectEn: 'Mathematics', fullMarks: 100, passMarks: 30, marksObtained: 92 },
    { subjectEn: 'Science', fullMarks: 100, passMarks: 30, marksObtained: 81 },
    { subjectEn: 'Social Science', fullMarks: 100, passMarks: 30, marksObtained: 76 },
    { subjectEn: 'English', fullMarks: 100, passMarks: 30, marksObtained: 68 }
  ];

  doc.setFont("Helvetica", "normal");
  doc.setTextColor(50, 50, 50);
  y += 8;

  subjects.forEach((subj) => {
    // Zebra background
    if (y % 16 === 12) {
      doc.setFillColor(250, 250, 250);
      doc.rect(15, y, 180, 8, "F");
    }
    doc.rect(15, y, 180, 8, "S");
    doc.text(subj.subjectEn, 20, y + 5.5);
    doc.text(String(subj.fullMarks), 85, y + 5.5);
    doc.text(String(subj.passMarks), 125, y + 5.5);
    
    // Highlight pass / fail
    if (subj.marksObtained < subj.passMarks) {
      doc.setFont("Helvetica", "bold");
      doc.setTextColor(220, 38, 38); // red
    } else {
      doc.setFont("Helvetica", "bold");
      doc.setTextColor(46, 125, 50); // green
    }
    doc.text(String(subj.marksObtained), 165, y + 5.5);
    doc.setFont("Helvetica", "normal");
    doc.setTextColor(50, 50, 50);

    y += 8;
  });

  // Footer / Result Summary Block
  y += 6;
  doc.setFillColor(247, 243, 238);
  doc.rect(15, y, 180, 20, "F");
  doc.setDrawColor(212, 82, 42);
  doc.rect(15, y, 180, 20, "S");

  doc.setFont("Helvetica", "bold");
  doc.setTextColor(26, 58, 92);
  doc.text(`Aggregate Percentage: ${results.totalPercentage}%`, 20, y + 7);
  doc.text(`Assigned Grade: ${results.grade}`, 130, y + 7);
  doc.text(`Performance Remark: ${results.remarksEn}`, 20, y + 14);

  // Certifying Signatures
  y += 40;
  doc.setFont("Helvetica", "mono");
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text("This report is digitally generated by Bihar Education Portal.", 15, y - 8);

  doc.setFont("Helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(26, 58, 92);
  doc.line(15, y, 65, y);
  doc.text("Tabulator In-charge", 20, y + 5);

  doc.line(145, y, 195, y);
  doc.text("Headmistress Stamp", 150, y + 5);

  doc.save(`OmarGHS_Report_Roll_${rollNo}.pdf`);
}

/**
 * Generates an official Certificate PDF
 */
export function exportCertificatePDF(cert: CertificateRequest) {
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4'
  });

  // Landscape dimensions: 297 x 210
  // Double vector border
  doc.setDrawColor(26, 58, 92);
  doc.setLineWidth(1.5);
  doc.rect(8, 8, 281, 194);
  doc.setLineWidth(0.5);
  doc.setDrawColor(212, 82, 42);
  doc.rect(10, 10, 277, 190);

  // Decorative corner crests
  doc.setFillColor(26, 58, 92);
  doc.rect(10, 10, 12, 12, "F");
  doc.rect(275, 10, 12, 12, "F");
  doc.rect(10, 188, 12, 12, "F");
  doc.rect(275, 188, 12, 12, "F");

  // Title Branding
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(26, 58, 92);
  doc.text("RAJYAKRIT OMAR GIRL'S +2 SCHOOL", 148.5, 30, { align: "center" });

  doc.setFontSize(11);
  doc.setTextColor(212, 82, 42);
  doc.text("Bishnupur, Begusarai, Bihar - Government of Bihar Institution", 148.5, 37, { align: "center" });
  doc.text("School BSEB Board Code: 26011 (Matric) / 84091 (Inter) | UDISE ID: 10201001210", 148.5, 43, { align: "center" });

  doc.setDrawColor(26, 58, 92);
  doc.setLineWidth(0.5);
  doc.line(60, 48, 237, 48);

  // Certificate Header
  doc.setFontSize(18);
  doc.setTextColor(194, 65, 12); // Amber-700
  doc.text(cert.type.toUpperCase(), 148.5, 62, { align: "center" });

  // Body content
  doc.setFont("Helvetica", "normal");
  doc.setFontSize(12);
  doc.setTextColor(50, 50, 50);

  let textBody = `This is to certify that Smt/Miss ${cert.studentNameEn}, daughter of respectable guardians ` +
                 `of Begusarai district, Bihar, was an authentic student of ${cert.className} in our institution ` +
                 `during the academic session ${cert.academicYear} under Class Roll Number ${cert.rollNo}.\n\n` +
                 `She has successfully cleared the institutional assessments with high merit. To the best of our ` +
                 `institutional records, she bears an exemplary moral character and displayed active interest in girls ` +
                 `sports and cultural programs. We wish her complete success in her higher educational pursuits.`;

  const splitText = doc.splitTextToSize(textBody, 220);
  doc.text(splitText, 148.5, 80, { align: "center" });

  // Facts panel
  doc.setFontSize(10);
  doc.setFont("Helvetica", "italic");
  doc.text(`Reference Number: ${cert.referenceNo}`, 30, 155);
  doc.text(`Date of Issue: ${cert.appliedDate}`, 30, 161);

  // Signatures
  doc.setFont("Helvetica", "bold");
  doc.setDrawColor(26, 58, 92);
  doc.line(190, 155, 250, 155);
  doc.text("Headmistress / Principal", 220, 161, { align: "center" });
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text("Rajyakrit Omar Girl's +2 School, Bihar Stamp", 220, 166, { align: "center" });

  doc.save(`Certificate_${cert.referenceNo}.pdf`);
}

/**
 * Generates an academic Timetable schedule list PDF
 */
export function exportTimetablePDF(className: string, schedule: TimetableEntry[]) {
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4'
  });

  doc.setDrawColor(26, 58, 92);
  doc.setLineWidth(1.5);
  doc.rect(8, 8, 281, 194);

  // Title
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(26, 58, 92);
  doc.text("RAJYAKRIT OMAR GIRL'S +2 SCHOOL", 148.5, 24, { align: "center" });
  
  doc.setFontSize(12);
  doc.setTextColor(212, 82, 42);
  doc.text(`Daily Class Schedule - ${className}`, 148.5, 31, { align: "center" });

  // Grid / Table position
  let y = 45;
  doc.setFillColor(26, 58, 92);
  doc.rect(15, y, 267, 10, "F");

  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.text("Day / वार", 20, y + 6.5);
  doc.text("Period 1", 55, y + 6.5);
  doc.text("Period 2", 90, y + 6.5);
  doc.text("Period 3", 125, y + 6.5);
  doc.text("Period 4", 160, y + 6.5);
  doc.text("Recess / मध्याह्न", 192, y + 6.5);
  doc.text("Period 5", 222, y + 6.5);
  doc.text("Period 6", 253, y + 6.5);

  doc.setFont("Helvetica", "normal");
  doc.setTextColor(40, 40, 40);
  y += 10;

  const daysList = Array.from(new Set(schedule.map(s => s.day))).sort();

  daysList.forEach((dayName) => {
    doc.setFillColor(248, 245, 240);
    doc.setDrawColor(220, 220, 220);
    doc.rect(15, y, 267, 18, "F");
    doc.rect(15, y, 267, 18, "S");

    doc.setFont("Helvetica", "bold");
    doc.setTextColor(26, 58, 92);
    doc.text(dayName, 20, y + 10.5);

    // Filter day's classes
    const dayClasses = schedule.filter(s => s.day === dayName).sort((a, b) => a.period - b.period);
    doc.setFont("Helvetica", "normal");
    doc.setTextColor(50, 50, 50);
    doc.setFontSize(8.5);

    let xCol = 55;
    dayClasses.forEach((cl, idx) => {
      if (idx === 4) { // Lunch
        doc.setFont("Helvetica", "bold");
        doc.setTextColor(212, 82, 42);
        doc.text("Lunch Break", 192, y + 10.5);
        doc.setFont("Helvetica", "normal");
        doc.setTextColor(50, 50, 50);
      }
      const x = idx >= 4 ? xCol + 30 : xCol;
      doc.text(cl.subjectEn, x, y + 8);
      doc.setTextColor(120, 120, 120);
      doc.text(cl.teacherEn, x, y + 13);
      doc.setTextColor(50, 50, 50);
      if (idx !== 4) {
        xCol += 35;
      }
    });

    y += 18;
  });

  y += 15;
  doc.setFont("Helvetica", "italic");
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text("* Note: Subject schedules may adapt depending on weekly science lab rotations and sports scheduling.", 15, y);

  doc.save(`Timetable_${className.replace(/\s+/g, '_')}.pdf`);
}
